version: "3.8"

services:
    app:
        build: .
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - "5173:5173"
        environment:
            - CHOKIDAR_USEPOLLING=true

volumes:
    node_modules:
